#!/usr/bin/env python
# coding: utf-8

# In[ ]:

INPLACE AND OUT OF PLACE _ 21104051

Q 1 :  DIFFERENCE BETWEEN IN PLACE AND OUT PLACE 

#IN PLACE

-In the In-place algorithm, we do not require any extra memory allocation. As soon as our algorithm executes output simply overwrite the input. Thus, It saves additional memory consumption.
-In the In-place algorithm, memory requirements for the output are independent of input size and should be constant.
 ...But has high time complexity
Examples : quick sort , bubble sort , selection , insertion sort.

# OUT OF PLACE

-Out-of Place algorithm is Opposite to the In-place algorithm, it is also called an Out-in-place algorithm.
-Its output depends on input size.
-Merge-sort algorithm is an example of an out-of-place algorithm. It requires extra space for merging and also increases time complexity.
- Another example is Radix sort  


get_ipython().set_next_input('Q.2 IMPLEMENTATION OF IN PLACE AND OUT PLACE IN INSERTION SORT');get_ipython().run_line_magic('pinfo', 'SORT')

1.Insertion Sort Using In-Place Algorithm

#include <iostream>
using namespace std;
(/Creating, Insertion, Sort, void, function)
void insertion_sort_IP(int arr[],int n){
    //Initialising variables i and j
    int i=0,j=i+1;
    while(j<=n-1){
        int temp=arr[j];
        while(i>=0){
            if(arr[i]>temp){
                arr[i+1]=arr[i];
                i--;
            }
            if(i==-1){arr[0]=temp;break;}
            if(arr[i]<=temp){arr[i+1]=temp;break;}
        }
        j++;
        i=j-1;
    }
    return;
}

2.Insertion Sort Using Out-Place Algorithm

void insertion_sort_OP(int arr[],int si,int ei){
    //si=starting index
    //ei=ending index
    if(si==ei){return;}
    int j=si+1;
    int temp=arr[j];
    while(si>=0){
        if(arr[si]>temp){
            arr[si+1]=arr[si];
            si--;
        }
        if(si==-1){arr[0]=temp;break;}
        if(arr[si]<=temp){arr[si+1]=temp;break;}
    }
    insertion_sort_OP(arr,si+1,ei);
}
(/Function, to, print, array)
void pfun(int arr[],int n){
    for(int i=0;i<n;i++){cout<<arr[i]<<" ";}
}
int main(){
    int n;
    //Taking Input array
    cout<<"ENTER NUMBER OF ELEMENTS IN THE ARRAY: ";
    cin>>n;
    int arr[n],arr2[n];//Two array with same size and elements
    cout<<"ENTER ELEMENTS OF ARRAY SEPERATED BY SPACE: ";
    for(int i=0;i<n;i++){cin>>arr[i];}
    //copying arr to arr2
    for(int i=0;i<n;i++){arr2[i]=arr[i];}
    cout<<endl;
    cout<<"ARRAY BEFORE SORTING : ";pfun(arr,n);
    //Calling insertion sort using in-place algorithm.
    insertion_sort_IP(arr,n);
    cout<<endl;
    cout<<"ARRAY AFTER SORTING USING IN-PLACE ALGORITHM : ";
    //printing the array
    pfun(arr,n);
    cout<<endl;
    //calling insertiong sort using out-place algorithm.
    insertion_sort_OP(arr2,0,n-1);"AS IT USES AN EXTRA MEMORY BASED ON INPUT SIZE"
    cout<<"ARRAY AFTER SORTING USING OUT-PLACE ALGORITHM : ";
    //printing the array
    pfun(arr,n);
    cout<<endl;

}
   
Q.3 PRACTICAL APPLICATIONS OF IN-PLACE AND OUT-PLACE

#IN - PLACE

1.For example if we want to reverse an array then its in-place algorithm will be swaping the first and last element of array until we reach the 
  middle of array,
2.In many cases, the space requirements of an algorithm can be drastically cut by using a randomized algorithm.
3. For example, say we wish to know if two vertices in a graph of n vertices are in the same connected component of the graph. There is no known simple, deterministic, in-place algorithm to determine this, but if we simply start at one vertex and perform a random walk of about 20n3 steps, the chance that we will stumble across the other vertex provided that it is in the same component is very high
    Similarly, there are simple randomized in-place algorithms for primality testing such as the Miller–Rabin primality test
4. There are also simple in-place randomized factoring algorithms such as Pollards rho algorithm. See RL and BPL for more discussion of this phenomenon.

#OUT-PLACE 

1.If we want to solve the same problem using out-place algorithm we have to create one extra array of same size and copy elements of original array from back to the front of new array,this 
 algorith increases the space complexity to O(n) as we have creaed an extra array.
2.merge sort is an example of out of place.
3.Now a days, using out-of-place sorting is a much better option because most of the computers offers decent amount of RAM. So even if this method of sorting uses extra memory, the program can still get executed.
then out of place algorithm can be used in editing the spreadsheet,browsing internet and performing day to day life easy tasks
4.we assume a person sing in a choir and when there’s free time I sort of pathologically sort the music. The choir members are assigned numbers so as to keep track of our personal performance “notes”, reminderts of the conductor’s nuances. I sort the music for a while, but soon it becomes a nuisance to hold the stack of books or thumb through to the right spot into which I then have to slip in the new entry. Thus I start a new stack, 
  and then…you guessed it. I merge sort the three or four piles into one group.
